### PR TITLE
removing unnecessery return statements,changing some clone methods et…

### PR DESCRIPTION
**Pull request by bq-wrongway**
…c. (suggest using cargo clippy --all -- -D warnings --verbose) to deal with format errors

### CODE REVIEW

**Comment by FaisalBinAhmed** [comment]
Hi thanks for opening up the PR. @bq-wrongway 👏 

I actually put those return statements on purpose. I am personally not a fan of implicit return. But I am willing to change those to be more idimotically rust. :)

Also, could you remove the .idea related files from the PR. Make sure to put the folder in .gitignore

**Comment by bq-wrongway** [comment]
sorry for idea file, corrected !r

**Comment by bq-wrongway** [comment]
Hey, i removed .idea file , sorry about that. 
Regarding implicit returns, its your choice, i think its good habit to get used to, since its idiomatic way.

**Review by FaisalBinAhmed — APPROVED** [review]
Looks good, and thanks for the effort.

**Pull request merged**
